export enum ContractStatus {
    PERFORMING = 'PERFORMING',
    OBSERVATION = 'OBSERVATION',
    SUBSTANDARD = 'SUBSTANDARD',
    DOUBTFUL = 'DOUBTFUL',
    DEFAULTED = 'DEFAULTED',
  }
  
export enum SecurityType {
  SUKUK = 'SUKUK',
  SAHAM = 'SAHAM',
  OBLIGASI = 'OBLIGASI',
}

export enum SecurityContract {
  // --- SUKUK ---
  IJARAH = 'IJARAH',
  MURABAHAH = 'MURABAHAH',
  MUDHARABAH = 'MUDHARABAH',
  MUSYARAKAH = 'MUSYARAKAH',
  WAKALAH = 'WAKALAH',
  WAKALAH_BIL_ISTITSMAR = 'WAKALAH_BIL_ISTITSMAR',
  ISTISNA = 'ISTISNA',
  MUSYARAKAH_MUTANAQISHAH = 'MUSYARAKAH_MUTANAQISHAH',

  // --- SAHAM ---
  SHARE_PURCHASE = 'SHARE_PURCHASE',
  SHARE_SUBSCRIPTION = 'SHARE_SUBSCRIPTION',
  SHARE_BUYBACK = 'SHARE_BUYBACK', 
  CONVERTIBLE_NOTE = 'CONVERTIBLE_NOTE',

  // --- FALLBACK ---
  UNSPECIFIED = 'UNSPECIFIED', 
  OTHER = 'OTHER',           
}



